In [30]:
"""1. Make a 2D List and find out the mean, min, max for the single row also for the whole list"""


import numpy as np
l=np.random.randint(1,10,size=(3,3))
print(l)

first_row_mean=np.mean(l[0])
first_row_min=np.min(l[0])
first_row_max=np.max(l[0])
print(f"1st Row MIN={first_row_min} MAX={first_row_max} MEAN={first_row_mean}")

second_row_mean = np.mean(l[1])
second_row_max=np.max(l[1])
second_row_min=np.min(l[1])
print(f"2nd Row MIN={second_row_min} MAX={second_row_max} MEAN={second_row_mean}")

third_row_mean=np.mean(l[2])
third_row_min=np.min(l[2])
third_row_max=np.min(l[2])
print(f"3rd Row MIN={third_row_min} MAX={second_row_max} MEAN={third_row_mean}")

overall_min=np.min(l)
overall_max=np.max(l)
print(f"Overall MIN={overall_min} MAX={overall_max}")

[[8 5 4]
 [3 6 4]
 [2 7 4]]
1st Row MIN=4 MAX=8 MEAN=5.666666666666667
2nd Row MIN=3 MAX=6 MEAN=4.333333333333333
3rd Row MIN=2 MAX=6 MEAN=4.333333333333333
Overall MIN=2 MAX=8


In [ ]:
"""1. Make a 2D List and find out the mean, min, max for the single row also for the whole list"""


In [31]:
"""2. take an input and print the factorial of that number"""
from math import factorial


x=int(input())
print(factorial(x))



2


In [32]:
"""3. 1 to 100 print using loop"""
for i in range(100):
    print(i + 1)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [38]:
"""4. List Unique Value"""
l=[1,2,5,3,1,5]
l=np.unique(l)
l=l*l
print(l)
# print(np.square(l))

[ 1  4  9 25]
