In [2]:
import numpy as np

In [ ]:
L = [1, 2, 3.14, 4, 5, 6, 7, 8, 9]
arr = np.array(L, dtype="int32")
print(arr, "\n")

In [17]:
three_by_five_zeros = np.zeros((3, 5), dtype=int)
print(three_by_five_zeros, "\n")

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] 



In [18]:
three_by_five_ones = np.ones((3, 5), dtype=float)
print(three_by_five_ones, "\n")

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 



In [19]:
a = L[:7:2]
print(a)

[1, 3.14, 5, 7]


In [20]:
three_by_five_pi = np.full((3, 5), 3.14)
print(three_by_five_pi, "\n")

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]] 



In [21]:
zero_to_twenty = np.arange(0, 21, 2)
print(zero_to_twenty)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [2]:
L2 = [(range(i,i+3)) for i in [2,4,6]]
print(L2)
L=[]
for i in [2, 4, 6]:
    L.append((range(i, i + 3)))
print(L)

[range(2, 5), range(4, 7), range(6, 9)]
[range(2, 5), range(4, 7), range(6, 9)]


In [23]:
b = np.array([range(i, i + 3) for i in [2, 4, 6]])
print(b)

[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [24]:
print(L, b)

[range(2, 5), range(4, 7), range(6, 9)] [[2 3 4]
 [4 5 6]
 [6 7 8]]


In [3]:
between_zero_and_one=np.linspace(0,1,5)
print(between_zero_and_one)

[0.   0.25 0.5  0.75 1.  ]


In [5]:
three_by_three_float_num=np.random.random((3,3))
print(three_by_three_float_num)

[[0.09907336 0.34350314 0.38662787]
 [0.65733534 0.70187813 0.68175812]
 [0.56584253 0.8350925  0.68708418]]


In [7]:
diagonal_matrix=np.eye(3)
print(diagonal_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
