> 2.
>>a)
>>>i.

In [1]:
# 2.a)i.

cost_p=int(input("Enter the Cost Price"))
selling_p=int(input("Enter the Selling Price"))
print("Loss" if cost_p>selling_p else "Profit")


Profit


> 2.
>>a)
>>>ii.

In [2]:
# 2.a)ii.

num=int(input())
l=[int(i) for i in str(num)]
for i in range(len(l)):
    l[i]=pow(l[i],3)

print("Armstrong Number" if sum(l)==num else "Not Armstrong Number")

Armstrong Number


>2.
>>b)
>>>i.

In [3]:
# 2.b)i.

n=int(input("Enter the size of the list"))
l=input().split()
l=[int(l[i]) for i in range(n-1)]
total=n*(n+1)//2
print("Missing number is",total-sum(l))



Missing number is 3


>2.
>>b)
>>>ii.

In [4]:
# 2.b)ii.

sen=input("Enter a sentence")
word=sen.split()
print(len(word))


1


>2.
>>c)
>>>i , ii ,iii

In [5]:
# 2.c)i. and ii

l=[1,3,2,5,3,3,3,4,5,4,6]
l=list(set(l))
print(l)

# 2.c)iii.
for i in range(len(l)):
    l[i] = pow(l[i], 3)
print(l)

[1, 2, 3, 4, 5, 6]
[1, 8, 27, 64, 125, 216]


>2.
>>d)
>>>i ,ii

In [1]:
# 2.d)i
import numpy as np

arr=np.random.randint(1,10,(3,3))
print(arr)
print("Max:",np.max(arr))
print("Min:",np.min(arr))

# 2.d)ii
print("1st row Min:", np.min(arr[0]))
print("2nd row Min:", np.min(arr[1]))
print("3rd row Min:", np.min(arr[2]))
print("---------------")
print("1st row Max:", np.max(arr[0]))
print("2nd row Max:", np.max(arr[1]))
print("3rd row Max:", np.max(arr[2]))



[[8 1 9]
 [1 6 4]
 [7 1 3]]
Max: 9
Min: 1
1st row Min: 1
2nd row Min: 1
3rd row Min: 1
---------------
1st row Max: 9
2nd row Max: 6
3rd row Max: 7


>2.
>>f)
>>>i , ii ,iii

In [ ]:
# 2.f)i. and ii

l = [1, 3, 2, 5, 3, 3, 3, 4, 5, 4, 6]
l = list(set(l))
print(l)

# 2.f)iii.
for i in range(len(l)):
    l[i] = pow(l[i], 3)
print(l)